# Load Numpy

In [1]:
import numpy as np


# THe basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#Get dimensions
a.ndim

1

In [5]:
#Get dimensions

b.shape

(2, 3)

In [7]:
#get Type
b.dtype

dtype('float64')

In [8]:
#Get size
a.itemsize

4

In [9]:
#Get the total size
a.size * a.itemsize

12

In [10]:
#Get the total size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [11]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
x.shape

(2, 7)

In [13]:
#Get Specific elements [r, c]
x[1][5]

13

In [14]:
#Get specific row
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#Get specific column
x[:,2]

array([ 3, 10])

In [16]:
#Getting a lot more fancy [startindex:endingindex:step]
x[0,1:6]

array([2, 3, 4, 5, 6])

In [ ]:
x[0,1:6:2]

In [ ]:
x[0,1:-1:2]

In [17]:
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
#change column 2 into all 5
x[:,2] = 5
print(x)

In [ ]:
#change column 3 into all 3 into 100 and 200
x[:,3] = [100,200]
print(x)

#3D example

In [ ]:
y = np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(y)

In [ ]:
#get the specific element from 3D = get the value 4
y[0,1,1]

In [ ]:
#get the specific element from 3D = get the value 6
y[1,1,0]

In [ ]:
#get the specific element from 3D = get the value 6 and 7 in subset column values
y[1,0,1:]

In [ ]:
#concatenate
np.concatenate((np.zeros((2,3)),np.ones((2,3), dtype="int32")), axis=0)

# Initializing different types of arrays

In [ ]:
#ALL 0s MATRIX
np.zeros((2,3))

In [ ]:
#all 1s matrix

In [ ]:
# Any other number (shape, value, datatype)
np.full((2,3),(99), dtype="float64")


In [ ]:
  # Any other number (full_like) use similar shape from existing array (shape, value, datatype)
np.full_like(x, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random decimal numbers from existing array use random_sample
np.random.random_sample(x.shape)

In [ ]:
# Random integer values
np.random.randint(100)

In [ ]:
# Random integer values
np.random.randint(-50,100, size=(3,3))

In [ ]:
# indentity matrix
np.identity(5)

In [ ]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

In [ ]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

# Be careful when copying an array

In [ ]:
a = np.array([1,2,3])
b = a
print(b)

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a) # 1 of array a is changed because it directly points the location

In [ ]:
# use copy() to retain the values of array a
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

# Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
print(a+b)

In [ ]:
a ** 2

In [ ]:
# take the sine of all the values
np.sin(a)

In [ ]:
 # tike the cosine of all the values
np.cos(a)

# Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

In [ ]:
#a * b



In [ ]:
# Matrix multiplication
np.matmul(a,b)

In [ ]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

# Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

In [ ]:
np.max(stats)

In [ ]:
# axis = 0 row; axis = 1 columns
np.max(stats, axis = 0) 

In [ ]:
np.sum(stats)

In [ ]:
 np.sum(stats, axis = 0)

In [ ]:
 np.sum(stats, axis = 1)

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)


In [ ]:
before.shape

In [ ]:
after = before.reshape(4,2)

In [ ]:
after

In [ ]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

In [ ]:
# horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

In [ ]:
np.hstack([h1,h2])

# Miscellaneous

# Load Data from File

In [ ]:
    filedata = np.genfromtxt('numericdatasample.txt', delimiter=",")
    filedata = filedata.astype('int32') # to typecast into integer
    filedata

# Boolean Masking and advance indexing

In [ ]:
filedata > 6

In [ ]:
filedata[filedata > 6]

In [ ]:
filedata

In [ ]:
# searching for any value in axis
np.any(filedata > 6, axis = 0)


In [ ]:
# searching for any value in axis
np.all(filedata > 6, axis = 0)

In [ ]:
# you can index with  a list in Numpy
a = np.array([ 7,  8,  9, 10,  7,  8,  9, 10,  7,  8,  9, 10])
a[[1,2,10]]

In [ ]:
(filedata > 3 ) & (filedata < 10)

In [ ]:
np.random.rand(4,2)

In [ ]:
y=np.genfromtxt('reuters21578 _enc.txt', delimiter=',', dtype='uint32', skip_header=1)

In [ ]:
x = np.random.rand(100,10, dtype='uint32')

In [ ]:
np.save("sample_uint_32",y)